### ISSUE TITLE
MP healing pets do not cast heals

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#345]
MP healing pets such as Medinos do not cast their healing nano on their owner or their targets with /pet heal. They just sit around doing nothing.

**Comment by portalerprk** [comment]
Fixed

**Comment by prkdrake** [comment]
Unfortunately not fixed - the healing pet is targeting itself rather than the player's nano target with their healing nano. Likely related to #378 and #373
