### ISSUE TITLE
Bug at character creation

### ISSUE THREAD

**Issue by Ashmodee79** [project-rubika/issues#359]
At the end of character creation, when clicking the Rubi-ka button, nothing happens, so I clicked it a second time, but the character was created on first attempt.
After I got back to character list, it was there.

**Comment by portalerprk** [comment]
Next time this happens we need a timestamp of when you faced the issue with as much accuracy as you can get. 

We'd need to check the logs.

**Comment by S4ff0** [comment]
i make a new characther choose agent named it agent007 clicked play and nothing happened; again again then i change name agent0007 and it starts; maybe a lenght name problem;

**Comment by Zolarix** [comment]
This happened to me at about 2024-01-17 14:15 - 2024-01-17 14:20 UTC.

**Comment by portalerprk** [comment]
I think it has to do with some professions default inventory/gear.

**Comment by TheTinkeringIdiot** [comment]
Issue occurred for me at 02:09 UTC Jan 23rd. Both times Opifex Female Martial Artists (Tinkerfite and Blahtest1). It occurred once for my last Opifex Female Martial Artist (Tinkerfite) as well, but I don't have the timestamp beyond some time January 18th. 

Tests from 02:10-02:21 UTC January 23rd:
The problem did not occur for a Solitus Female Martial Artist (CCTest2). 
It did occur for a Opifex Male Martial Artist (CCtest3).
It did occur for a Opifex Female Nanotechnician (Cctest4).
It did occur for a Nanomage Female Nanotechnician (Cctest5).
It did occur for a Nanomage Male Martial Artist (Cctest6).
It did occur for a Atrox Martial Artist (Cctest7).
It did occur for a Opifex Female Meta-Physicist (Cctest8).

**Comment by prkdrake** [comment]
Tried with a huge number of breed/profession combinations locally and was unable to reproduce this - the issue has either been fixed on Ithaca (unlikely) or it is probably unrelated to breed/profession.

**Comment by TheTinkeringIdiot** [comment]
Could this be due to Newland City not being available? I had a character stuck in one of the Newland shops, unable to leave because "area change not initiated on the server". Rolling a new character experienced this issue immediately afterward.

**Comment by Zolarix** [comment]
> Could this be due to Newland City not being available? I had a character stuck in one of the Newland shops, unable to leave because "area change not initiated on the server". Rolling a new character experienced this issue immediately afterward.

The reason I don’t think this is the case is because I’ve rolled quite a few characters now where nothing happens when I press the RK button, so within 5 seconds I go back to character select and click the new character and it consistently logs me in to Newland City. You would expect sometimes when logging in from character select it would fail.

**Comment by prkdrake** [comment]
> "area change not initiated on the server"

This is almost always a teleportation bug, which has been fixed now, but it used to be that if you somehow teleported while inside a proxy playfield such as a shop, you got stuck in it unless you teleported out again. Most commonly this was caused by someone using /set level inside a shop

If NLC was unavailable, you'd just get stuck at a loading screen before the game disconnected

**Comment by TheTinkeringIdiot** [comment]
Issue remains present, encountered again just now rolling a new Opifex Fixer.

**Comment by kajoriEU** [comment]
still happens as of today, workaround remains to quit character creation and just log in normally.

Rubi-Ka button greys out and nothing happens (instead of logging in and spawning on ICC shuttleport)

![195b70b9-27e0-4a13-9eea-20deae4ff318](https://github.com/user-attachments/assets/28232688-5e69-4ad6-b907-8fb024b27424)

Character appears on character selection screen and you can log in normally.

![photo_5393577457841464785_w](https://github.com/user-attachments/assets/f22c0d85-9744-471a-884e-0b82d0ae828f)
