### ISSUE TITLE
Killed mobs respawn unnaturally quickly

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#424]
**Describe the bug**
High Spawn rate on the Muggers in the Subway
**To Reproduce**
1. Kill a mugger
2. Watch it respawn relatively quickly

**Expected behavior**
Muggers should take a bit longer to respawn!

**Comment by Enfodoug** [comment]
That does not only count for muggers. It counts for many mobt ypes around RK. 
Was killing robots at the Trash King an they respawned within a minute or so. 
Including The Trash Kinf and all his lackeys.

**Comment by prkdrake** [comment]
From personal experience, Trash King and friends should take somewhere around 20-30 minutes to respawn.

**Comment by 3F1-1009** [comment]
Trash King should be on 20 minute timer and Trash King Lackey on 7 minutes.

**Comment by reneraen** [comment]
@prkdrake : could you update this to be a bit more generic, since it's not connected to mugger (or subway) specifically. All mobs currently have an insane respawn rate (like uklesh etc).

**Comment by RaggyLP** [comment]
The 'Newbie Dyna' in Neut Backyards respawns instantly.

Extended location information:
- 52.8, 110.3, 4.9 (52.8 110.3 y 4.9 954)
- Pf Proxy: Model=51100:954 GS=0 SG=0 R=954, resource: 954
- zone: 17, area: "Junkyard"
Server id: 1, character id: 50000:764, time: 2024-01-18 00:27:46 (UTC)
Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.

**
![image](https://github.com/project-rubika/issues/assets/156821187/edc25419-6b43-4426-94bb-0859499b5c32)
**

**Comment by prkdrake** [comment]
Affects many NPCs, spawn rates seem to be much too high.

**Comment by reneraen** [comment]
To be honest, @prkdrake ... I thought this was intentional to actually test various npcs/special mobs... the amount of mobs with this "insanely quick" respawn rate probably applies to almost all mobs.

**Comment by prkdrake** [comment]
It's not intentional, and nothing immediately jumps out at me when looking at the code.

**Comment by prkdrake** [comment]
I think this should now be fixed, could someone please take a look and confirm? Thank you!

**Comment by Enfodoug** [comment]
It is not fixed.

![image](https://github.com/project-rubika/issues/assets/156118657/6e33991b-85ca-46ad-9039-6f7f39f16a3f)

![image](https://github.com/project-rubika/issues/assets/156118657/c0e8376a-af68-46e4-b2e3-32a12cdc8146)

**Comment by 3F1-1009** [comment]
Filth Fleas respawn time is around 8 minutes plus/minus some

**Comment by prkdrake** [comment]
> It is not fixed.
> 
> 
> 
> ![image](https://github.com/project-rubika/issues/assets/156118657/6e33991b-85ca-46ad-9039-6f7f39f16a3f)
> 
> 
> 
> ![image](https://github.com/project-rubika/issues/assets/156118657/c0e8376a-af68-46e4-b2e3-32a12cdc8146)

I think you have confused this ticket with another ticket. The fix for this ticket is nothing to do with the floating corpses.

**Comment by Enfodoug** [comment]
> I think you have confused this ticket with another ticket. The fix for this ticket is nothing to do with the floating corpses.

Indeed.

**Comment by RaggyLP** [comment]
Tested by obliterating the first part of Subway, everything took a lot longer to respawn, definitely closer to expected on Live. Trash King also seems to be on a reasonable timer now and isn't popping back up immediately. Appears fixed as of 17:44 UTC - 01/02/24
