### ISSUE TITLE
Some items when sold to the store show a high sale value but remove money when sold.

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#425]
**Describe the bug**
Some items when sold to the store show a high sale value for their QL level, but seem to instead take away ~10 percent of the shown store terminal value.  

This was witnessed with a QL: 9 Qualtiy MTI Alpeh 99 (`.item 152326 152327 9`) looted from a Mugger in the Borealis Subway.  

**To Reproduce**
1. Go to any trade terminal/shop terminal
2. Drop the item in question in the shop terminal
3. Observe the price that it  is supposed to give.
4. Sell the item.
5. Observe your balance

**Expected behavior**
That the amount listed in the box for "Sold Items" is in proportion to the item and it's QL, and that the money is given, rather than taken away. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/43483963/34b3f057-1005-4b67-b55b-2c917079d491)

Look at the Credits offered and the total credits I have for each screenshot

![image](https://github.com/project-rubika/issues/assets/43483963/f7859ffa-86a1-44d5-8829-847fc020f1e2)

**Comment by prkdrake** [comment]
This should now be fixed, could someone please verify this and let us know? Thank you!

**Comment by playboyfixer** [comment]
still happening, tried with same gun as mentioned in original report:
![image](https://github.com/project-rubika/issues/assets/156527345/176c7617-4bce-4838-8d61-62d94343e0e9)
![image](https://github.com/project-rubika/issues/assets/156527345/df7872a5-d586-4a84-8953-24792046938a)
![image](https://github.com/project-rubika/issues/assets/156527345/6bf7a7b9-da96-4eb8-a6e9-3ca132579a1d)

**Comment by prkdrake** [comment]
Should be fixed now, please re-test and let us know, thanks :)

**Comment by TheTinkeringIdiot** [comment]
Tested several items in a shop and all gave the appropriate number of credits for the sale. This appears to be fixed.
