### ISSUE TITLE
Enemies drop 1 unit of ammo as part of their loot pool

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#436]
**Describe the bug**
When killing enemies, they will occasionally drop ammo.  But whenever they do it'll only be in single units.   1 Energy, 1 Bullet, 1 Arrow, etc 

**To Reproduce**
1. Kill an enemy
2. View loot
3. If loot is any sort of ammo it'll be one unit

**Expected behavior**
Ammo if memory serves tend to drop in stacks of 100.

**Comment by prkdrake** [comment]
This should now be fixed, could someone please verify this and let us know? Thank you!

**Comment by playboyfixer** [comment]
Still happening in subway
![image](https://github.com/project-rubika/issues/assets/156527345/655eded0-09c5-439f-b483-0b468d07459d)

**Comment by 3F1-1009** [comment]
Looters and Muggers both drop only 1

**Comment by playboyfixer** [comment]
mine was a vagabond, but the other 2 confirmed too dropping 1

**Comment by Random823** [comment]
Tested, not sure if something change since playboyfixer's comment but mugger drop 100 Energy Weapon Ammo.

Confirmed working.

**Comment by prkdrake** [comment]
Thanks - yeah, the fix got accidentally reverted the other day, but has been reapplied :P
