### ISSUE TITLE
Setups not importing correctly

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#550]
**Describe the bug**
The new .setups command applies textures and partial skills, but not the entire setup. 

I am importing https://www.aosetups.com/equip/65b088f2c9bb2231eaa9d733 using the command `.setups import -blps 65b088f2c9bb2231eaa9d733`. Chat confirms that the command executed successfully. My character has the appropriate skins for the selected armor, but all wear tabs are empty. Getfull command output seems to indicate that the desired gear is worn, but it does not appear in the Wear menu. 

Additionally the Abilities tab in the IP menu are maxed as the AOSetup profile specifies (well, close - each ability is 8 points short of max). Run speed is 500 or so short of max. Others haven't been raised at all. 

This condition persists through relog and zone. 

**To Reproduce**
1. Log in to character
2. `.setups import -blps 65b088f2c9bb2231eaa9d733`
3. Setups command reports success, and armor textures are applied, but Wear menu remains empty. IP are only partially spent

**Expected behavior**
As I understand it the setups command should apply the existant items from the given AOSetups profile to the character. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/61d68294-355d-4c25-ad88-66a82419aa4c)

**Character info:**

```
Tinkernukes [220 Nanotechnician]
------------------------------------
    strength 	766
    stamina 	786
    agility 	784
    sense 	794
    psychic 	857
    intelligence 	857
    flags 	528961
    monsterscale 	100
    currentnano 	7679
    headmesh 	2000000001
    cash 	0
    gmlevel 	127
    expansion 	3
    breed 	1
    visualbreed 	1
    profession 	11
    visualprofession 	11
    level 	220
    sex 	3
    visualsex 	3
    titlelevel 	7
    health 	6793
    equippedweapontype 	1
    EquippedRHWeapon 	1
    exitstatel 	-1073740638
    externaldoorinstance 	-1073216970
    externalplayfieldinstance 	566
    playfieldtype 	1
    selectedtarget 	1119
    nextxp 	3067008
    xp 	2555840
    lastsaved 	2555840
    lastxp 	2555840
    side 	1
    alignment 	1750
    bodydevelopment 	1131
    runspeed 	1182
    senseimprovement 	1339
    treatment 	1140
    materialmetamorphose 	1349
    biologicalmetamorphose 	1334
    psychologicalmodification 	1346
    materialcreation 	1345
    materiallocation 	1305
    nanoenergypool 	1313
    nanoprowessinitiative 	1362
    nanoprogramming 	1379
    computerliteracy 	1349
    maxnanoenergy 	7679
    perception 	243
    pistol 	229
    firstaid 	234
    dodge 	236
    lr_energyweapon 	235
    evade 	238
    distanceweaponinitiative 	234
    duck 	246
    nanoac 	10
    concealment 	207
    maxncu 	64
    selectedtargettype 	0
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	6793
    monsterdata 	0
    VisualFlags 	31
    isfightingme 	0
    currentmovementmode 	3
    clan 	0
    martialarts 	205
    team 	0
    meleeac 	5960
    projectileac 	5810
    energyac 	9635
    fireac 	7210
    coldac 	7210
    radiationac 	9635
    chemicalac 	7210
    poisonac 	7210
    poisondamagemodifier 	6
    radiationdamagemodifier 	16
    chemicaldamagemodifier 	6
    colddamagemodifier 	6
    firedamagemodifier 	6
    projectiledamagemodifier 	6
    energydamagemodifier 	6
    meleedamagemodifier 	6
    npcostmodifier 	-5
    xpmodifier 	7
    nanodelta 	27
    healinterval 	3
    nanointerval 	1
------------------------------------

.getfull succeeded - Listed all stats for Tinkernukes.

```

**Comment by prkdrake** [comment]
I suspect what happened here is that you somehow interrupted the import part-way through. The import can be a bit slow sometimes - I am planning to look into speeding it up - but I let it run all the way to completion with your example and it seemed to work for me - though I also see that the skills are lacking a few - attributes are missing 6 and other skills missing 5. I suspect it has something to do with the starting level of skills.

**Comment by prkdrake** [comment]
Tested it on Ithaca and it was relatively quick, though Symbiants aren't coming in - need to take a look at why that is.

**Comment by TheTinkeringIdiot** [comment]
Thanks for taking a look. What's an average time frame the setups are generally done in? And can the success message be delayed until that point?

**Comment by prkdrake** [comment]
The success message shouldn't show up until it has completed, so that's potentially an issue - timeframe really depends on the server. I tested it pretty much just after a reboot and it was done in a second or less, but when I run it locally (without the item precaching that Ithaca does) it takes ~30 seconds. I've found the issue with symbiants and working on fixing that now.

**Comment by prkdrake** [comment]
Okay, the issues from this issue should now be fixed, hopefully! Could you please re-test at your convenience and let us know? Thank you :)

**Comment by TheTinkeringIdiot** [comment]
The fixes did not solve the problem for that character, but they did solve the problem in general. The character I reported this on remained broken as before - .setups did not apply equipment, and after attempting the .setups command no other dot commands worked either. 

Two newly rolled characters work as intended, though, so I think we can chalk this one up to a broken character and call it fixed.
