### ISSUE TITLE
The 'Debuff NanoAC Heavy' line (Trader) cannot be used.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#581]
**Describe the bug**
The 2nd tier of the casting structure currently cannot be cast. Giving a generic 'Unable to execute nano program. You can't execute this nano on the target.' error.

**To Reproduce**
1. Find a combat target.
2. Cast the first part of the debuff tier (Eviscerate Defense)
3. Attempt to cast the second part. (Attenuate Defense)
4. Observe error.

**Expected behavior**
The Trader 'Debuff NanoAC Heavy' line checks for a pre-existing nano in the target's NCU and then allows the cast of the higher debuff.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/dcd6bab8-8109-4c1d-8b41-1d6b8c787695)

**Character info:**

```
Raggy [220 Trader]
------------------------------------
    strength 	1634
    stamina 	2221
    agility 	1883
    sense 	1810
    psychic 	2225
    intelligence 	2230
    flags 	528961
    monsterscale 	100
    currentnano 	8885
    headmesh 	223891
    cash 	21883
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	7
    visualprofession 	7
    level 	220
    sex 	2
    visualsex 	2
    titlelevel 	7
    health 	10186
    equippedweapontype 	8196
    EquippedRHWeapon 	8196
    selectedtarget 	1028
    nextxp 	3067008
    xp 	2555840
    lastsaved 	2555840
    treatment 	4873
    lastxp 	2555840
    currentncu 	40
    runspeed 	2752
    senseimprovement 	2807
    biologicalmetamorphose 	2837
    psychologicalmodification 	2816
    materialcreation 	3834
    materiallocation 	3817
    nanoprowessinitiative 	2739
    shotgun 	5001
    distanceweaponinitiative 	2545
    computerliteracy 	3772
    nanoenergypool 	2073
    martialarts 	2488
    brawl 	2472
    riposte 	2466
    dimach 	2478
    adventuring 	2625
    swim 	2701
    onehandbluntweapons 	2478
    onehandedgedweapon 	2482
    piercing 	2571
    twohandbluntweapons 	2486
    twohandedgedweapons 	2472
    meleeenergyweapon 	2561
    parry 	2522
    sneakattack 	2498
    meleemultiple 	2465
    fastattack 	2468
    throwingknife 	2537
    grenade 	2677
    throwngrapplingweapons 	2637
    bow 	2456
    pistol 	2743
    assaultrifle 	2719
    submachinegun 	2700
    rifle 	2468
    lr_energyweapon 	2520
    flingshot 	2760
    aimedshot 	2512
    burst 	2528
    fullauto 	2664
    bowspecialattack 	2545
    lr_multipleweapon 	3506
    closecombatinitiative 	2490
    physicalprowessinitiative 	2490
    dodge 	3589
    evade 	3717
    duck 	2798
    nanoac 	2280
    mechanicalengineering 	2739
    electricalengineering 	2756
    fieldquantumphysics 	2781
    weaponsmithing 	2843
    pharmaceuticals 	2765
    nanoprogramming 	2802
    psychology 	2795
    chemistry 	2781
    tutoring 	2816
    materialmetamorphose 	2837
    firstaid 	2686
    concealment 	2737
    breakingentry 	2578
    disarmtrap 	2565
    perception 	2789
    driveair 	2757
    driveground 	2757
    drivewater 	2757
    mapnavigation 	2779
    maxnanoenergy 	8885
    side 	1
    selectedtargettype 	0
    charstate 	0
    exitstatel 	-1073740870
    externaldoorinstance 	-418378760
    externalplayfieldinstance 	3064
    playfieldtype 	0
    isfightingme 	1
    life 	10186
    waitstate 	1
    bodydevelopment 	2295
    expansionplayfield 	0
    secondaryitemtemplate 	207108
    specialization 	15
    maxncu 	2091
    fatness 	1
    race 	1
    accountflags 	1234567890
    monsterdata 	0
    VisualFlags 	31
    currentmovementmode 	3
    clan 	0
    projectileac 	24914
    energyac 	25664
    meleeac 	23704
    coldac 	25597
    fireac 	24660
    chemicalac 	24387
    radiationac 	26347
    poisonac 	24914
    healdelta 	165
    nanodelta 	124
    procnano1 	210941
    procinitiative1 	4
    procchance1 	17
    team 	0
    dmsmodifier 	343
    amsmodifier 	21
    rangeincreaserweapon 	7
    rangeincreasernf 	31
    firedamagemodifier 	19
    poisondamagemodifier 	19
    projectiledamagemodifier 	19
    radiationdamagemodifier 	19
    chemicaldamagemodifier 	19
    xpmodifier 	9
    npcostmodifier 	-8
    skilllockmodifier 	-25
    interruptmodifier 	-25
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	1
    nanointerval 	1
    reflectreturnedmeleeac 	0
    reflectmeleeac 	0
    shieldmeleeac 	0
    reflectreturnedradiationac 	0
    reflectradiationac 	0
    shieldradiationac 	0
    reflectprojectileac 	0
    reflectenergyac 	0
    reflectfireac 	0
    reflectcoldac 	0
    reflectchemicalac 	0
    reflectpoisonac 	0
------------------------------------

.getfull succeeded - Listed all stats for Raggy.
```

**Comment by TheTinkeringIdiot** [comment]
Confirmed using the given steps. The same occurs for Blunt Defense and Cripple Defense in the same line.

**Comment by portalerprk** [comment]
I believe this was also fixed with project-rubika/engines#390 

Please test when your able.

**Comment by RaggyLP** [comment]
Re-tested, still unable to cast the 2nd part of the NanoAC debuff. Outputs a generic error.
![image](https://github.com/project-rubika/issues/assets/156821187/76961515-fd89-4a92-9b4d-a9d9a3ea9ff0)

**Comment by RaggyLP** [comment]
Retested again, it is now working as expected, a futher issue has reared its head in the fact there is discrepancies on NPCFamily type for some NPCs (those spawned in the BY for example are listed as 0).

**Comment by RaggyLP** [comment]
Confirmed fixed, the whole nanoline can now be used and is reflected in getfull when used on a mob wiht the correct NPCFamily value. Fixed as of 21:39 UTC - 19/02/24

![image](https://github.com/project-rubika/issues/assets/156821187/0035a029-1a48-43b7-be30-ccab1f27890d)
![image](https://github.com/project-rubika/issues/assets/156821187/05197d3d-02c9-4e14-9bae-a4c8b3e48201)
