### ISSUE TITLE
Outdoor mobs cannot be fought

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#586]
**Describe the bug**
When attacking an outdoor mob in higher level zones (ones with enough health they don't instantly die when attacked), they will respond by giving chase for a short distance, then stop for several seconds before "twitching" (as if they're respawning rapidly) and spamming chat with "Attacked by <mob name>" messages. This behavior continues indefinitely and while it occurs auto-attacks pause and hostile nano programs cannot be used. 

Hostile perk actions can be used and do land, but other types of attacks do not work. 

Moving away can cause the mob to be "normal" again for a short time until you stop and engage, at which point it will resume spamming and being unattackable. 

**To Reproduce**
1. Go to a higher level zone. I tested EFP and Avalon.
2. Find a "normal mob"
3. Engage it in combat
4. It chases normally for a short time
5. Then it "twitches", visually glitching
6. Chat is spammed with "Attacked by <mob>" messages
7. Mob cannot be attacked other than with perk actions

**Expected behavior**

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/2b056141-b45b-4399-abd3-48417af8eb1a)

![image](https://github.com/project-rubika/issues/assets/96996793/f2f1658d-6e35-4093-9f0d-e7d1f558651e)

![image](https://github.com/project-rubika/issues/assets/96996793/3a980d1d-a89b-40a0-9d08-79cec887d13d)

**Playfield info:**

```
In the screenshots - chat was spamming
```
----

**Comment by RaggyLP** [comment]
Confirmed. There appears to be a disconnect between the location the client is reporting the mobs to be and where the server thinks it is. You can see evidence of this at the end of the video when the mob corpse is placed miles away.


https://github.com/project-rubika/issues/assets/156821187/1196b756-761a-46f4-8c0b-b8a4956973f5

**Comment by TheTinkeringIdiot** [comment]
While troubleshooting, I was wondering if it might be at all related to #347, since they exhibit some of the same behavior when pathing.

**Comment by prkdrake** [comment]
This should be fixed now, please test and let us know! Thanks

**Comment by RaggyLP** [comment]
Sadly not fixed. Please see attached vid.

https://github.com/project-rubika/issues/assets/156821187/49ff1de6-cff5-4c49-be7d-74574e691071

**Comment by prkdrake** [comment]
It's looking a lot better than it was, but yeah, pathfinding still sucks, unfortunately.

**Comment by RaggyLP** [comment]
> It's looking a lot better than it was, but yeah, pathfinding still sucks, unfortunately.

Yeah, there are still situations where the attack bars get totally jammed, but it seems a bit cleaner in that regard. Progress!
