### ISSUE TITLE
Refreshing nanos in the NCU check MaxNCU even if already present.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#849]
**Describe the bug**
When attempting to refresh a nano that is already present in the players NCU, the error 'Target does not have enough nano controlling units (NCU) left.' is displayed. This is really noticable with nanos such as drains, as attempting to refresh the buff portions whilst having less NCU than they would otherwise require, results in the duration not updating.

**To Reproduce**
1. Create a Trader for ease of testing.
2. `.set maxncu 10`
3. On a target: `.ncu run 85868`
4.  Let the duration drop a bit for ease of viewing.
5. Cast again `.ncu run 85868`
6. Notice no updated duration and error message printed.

**Expected behavior**
Nanocasts should not be taking MaxNCU into consideration if the nano is already running in the NCU.

**Screenshots**
![image](https://github.com/user-attachments/assets/8c989190-60bb-4c8c-8902-7793c71ba197)

**Comment by kajoriEU** [comment]
Latest update fixed this issue 👍 

Closing this as fixed as of 24/09/2024!

**Comment by Nephima** [comment]
Adding here as it's related - recasting the same Nano that is already running works. But casting a different Nano within the same Nanoline to update the lesser Nano fires a "not enough NCU" message. To test:
.set MaxNCU 11
.ncu run 85870 (this requires 5 NCU)
.ncu run 85866 (this requires 11 NCU)
Theoretically the second cast should work as it fits within 11 NCU limit but it doesn't.

**Comment by StormlashTV** [comment]
Also, if you have 4 free NCU, let's say 18/22, and try to buff yourself with a nano that costs 4 NCU that is currently not in your NCU window, it won't let you do it. You get the following: "Target does not have enough nano controlling units (NCU) left."

**Comment by prkdrake** [comment]
This should now be fixed

**Comment by Hexmyth** [comment]
I'm still encountering "Not enough NCU" messages when I have exactly sufficient NCU (no versions of the same nanoline or anything).

**Comment by kajoriEU** [comment]
> I'm still encountering "Not enough NCU" messages when I have exactly sufficient NCU (no versions of the same nanoline or anything).

This seems to be tied to another problem :) Will open up a separate issue for it.

**Comment by kajoriEU** [comment]
closing this issue for now as we're unable to reproduce the problem. If you encounter this issue again, please feel free to reopen it.
