### ISSUE TITLE
Kill the Malah-Fama Prophetess - Expected quest item is not spawned in inventory on kill. [Elysium Yutto Quest]

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#908]
**Describe the bug**
The quest Kill the Malah-Fama Prophetess requires you to kill a nearby mob, which is flanked by 2 very strong Hiathlins. Upon killing the Malah, she drops her eye, which is required to hand in to the Yutto who grants the quest.

**To Reproduce**
1. `.quests add 5IMC`
2. `.tp 1315.2 868.1 y 45.8 4544`
3. ~~`.npc loot` - Shows the eye is not in the loot table.~~
4. Kill the Prophetess

**Expected behavior**
The mob should drop 259805 on death. The item appears to be missing from its loot table.

**Comment by prkdrake** [comment]
Having looked at the data, I think the eye is actually an item reward you receive on killing the enemy, rather than an item you loot from the enemy - could that be the case? Or should the eye definitely be on the enemy's corpse?

**Comment by prkdrake** [comment]
This should be fixed by an upcoming update.

**Comment by kajoriEU** [comment]
Partially resolved.

After defeating Malah-Fama Prophetess, the Eye of the Prophetess now appears in the inventory.

However, 'One Who Overcomes Enemies' still does not recognize the item as the correct one needed to complete the quest.

![{420E99CD-2D18-48EF-8A30-7B62719BB7F4}](https://github.com/user-attachments/assets/cad5f9e0-e3d7-4bc9-9f08-5c416c57be3b)

https://github.com/user-attachments/assets/9cdda31e-f6d7-4046-98a8-2a5aab257bdf

**Comment by kajoriEU** [comment]
The quest step checks that the player character's level does not exceed 201. During my testing, I made an error, but it now appears that the quest functions correctly when the character's level is below 201.

So closing this as fixed as of 15/09/2024
