### ISSUE TITLE
Acolytes in TOTW heal you while in combat

### ISSUE THREAD

**Issue by donkeyohtay** [project-rubika/issues#951]
### Reproduction steps

```bash
1. Go to TOTW
2. Enter combat with Acolyte Seleen
3. She will cast a heal on you
```

### Expected results

```bash
Should heal herself I think?
```

### Actual results

```bash
She spams the heal on you instead of herself.
```

### Bug prevalence

Every fight

### Description

```bash
She will also heal you through LOS, even if you block it with a pillar or a wall.
```

### Report link

https://pastebin.com/0Sv3d1bi

**Comment by donkeyohtay** [comment]
Looks like Reverends do this as well.

**Comment by kajoriEU** [comment]
Confirmed 👍 We're in the process of reworking targeting, which is causing NPCs to behave this way.

**Comment by RaggyLP** [comment]
Confirmed.

![image](https://github.com/user-attachments/assets/49dd3a71-1235-4003-b332-11f12aaefb33)
![image](https://github.com/user-attachments/assets/4cc9f8b6-ad48-404e-bd26-1cacd4bd7328)

Closing as fixed as of 20/09/2024

**Comment by Nephima** [comment]
This is still happening, I am still being healed by Exarch Gevarain and Pilvar in ToTW.

**Comment by kajoriEU** [comment]
I'm reopening this ticket because the issue appears to be the same one that was previously addressed with a fix.

This seems to be happening on all Exarchs and Windcallers in TOTW.
